In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
#NLP Libraries
import nltk
import re
from nltk.corpus import stopwords
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
#Deep Learning Libraries
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Bidirectional

#Vocabulary Size
vocab_size=5000

In [ ]:
#Mount at drive
import sys
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Identifying Suicidal Intent through Depression Detection from Texts using Machine Learning Techniques/Dataset/Original Dataset/Suicide and Depression Detection.csv')
df.head(10)

Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1           3  Am I weird I don't get affected by compliments...  non-suicide
2           4  Finally 2020 is almost over... So I can never ...  non-suicide
3           8          i need helpjust help me im crying so hard      suicide
4           9  I’m so lostHello, my name is Adam (16) and I’v...      suicide
5          11  Honetly idkI dont know what im even doing here...      suicide
6          12  [Trigger warning] Excuse for self inflicted bu...      suicide
7          13   It ends tonight.I can’t do it anymore. \nI quit.      suicide
8          16  Everyone wants to be "edgy" and it's making me...  non-suicide
9          18  My life is over at 20 years oldHello all. I am...      suicide

In [ ]:
Class={'self.Anxiety':0, 'self.bipolar':0, 'self.depression':1,'self.SuicideWatch':1, 'self.offmychest':0}
df=df.replace({"label":Class})
df = df.rename(columns={"label": "class"})
df.head(10)

text  class
0  I can't make money I can't live in a world whe...      0
1  "How are you?" "I'm fine," "How are you?" "I'm...      0
2  I'm fed up I'm fed up with all this world, it'...      1
3  Can depression "evolve" to bipolar over time w...      0
4  Any words of encouragement Hello I posted year...      1
5  I miss the girl who made my life shit for a ye...      0
6  Just because you don't understand it doesn't m...      0
7  I didn't vote last year and now I don't feel I...      0
8  I don't think my crush is interested in me at ...      0
9  motivation please I hate to come here for this...      0

In [ ]:
df.drop(["Unnamed: 0", "Positive", "Negative", "Neutral", "Compound"],axis=1, inplace=True)
df = df.rename(columns={"Sentiment": "class"})
df.head(10)

text  class
0  after all i was stupid to be used because i wo...      1
1  of course ido not want to die but it is suffer...      1
2  whatever this new accusation is it has beaten ...      1
3  passed in great anxiety finally painted the ba...      1
4  the most charming intelligent and important pe...      0
5  it has prevented my getting anything like the ...      0
6  i hve receved hate letters telling me to leave...      1
7                  i was burning in hell every day .      1
8  or write faggot on my locker or send me letter...      1
9  it is like they beat the hellout of me with th...      1

In [ ]:
df.drop(["Unnamed: 0"],axis=1, inplace=True)
Class={"non-suicide":0,"suicide":1}
df=df.replace({"class":Class})
df.head(10)

text  class
0  Ex Wife Threatening SuicideRecently I left my ...      1
1  Am I weird I don't get affected by compliments...      0
2  Finally 2020 is almost over... So I can never ...      0
3          i need helpjust help me im crying so hard      1
4  I’m so lostHello, my name is Adam (16) and I’v...      1
5  Honetly idkI dont know what im even doing here...      1
6  [Trigger warning] Excuse for self inflicted bu...      1
7   It ends tonight.I can’t do it anymore. \nI quit.      1
8  Everyone wants to be "edgy" and it's making me...      0
9  My life is over at 20 years oldHello all. I am...      1

In [ ]:
df_manual_testing = df.tail(10000)
for i in range(1,10001,-1):
    df.drop([i], axis = 0, inplace = True)

In [ ]:
df=df_manual_testing

In [ ]:
df.drop(["Unnamed: 0","Unnamed: 0.1","title","selftext","author","num_comments","url","title_clean","author_clean","selftext_length","title_length","megatext_clean"], axis=1, inplace=True)
df = df.rename(columns={"selftext_clean": "text"})
df = df.rename(columns={"is_suicide": "class"})
df.head(10)

class                                               text
0      0  hi really know phrase situation try life reall...
1      1  depressed past couple week ever since got back...
2      0  hi know else go devastated right feeling like ...
3      1  shit like get better everyone purpose need fin...
4      0  wish wa prettier wish feel like burden wish br...
5      1  weird question someplace call talk someone go ...
6      0  venting void feel bad constantly annoying frie...
7      0  hey guy last week went roughest day ocd ha eve...
8      1  know pas know many people know care want say p...
9      0  fighting depression couple year ha uphill batt...

In [ ]:
df.drop(["User"],axis=1, inplace=True)
Class= {"Ideation": 1, "Supportive": 0,"Attempt":1,"Behavior":1,"Indicator":1}
df = df.rename(columns={"Post": "text"})
df=df.replace({"Label":Class})
df = df.rename(columns={"Label": "class"})
df.head()


text  class
0  ['Its not a viable option, and youll be leavin...      0
1  ['It can be hard to appreciate the notion that...      1
2  ['Hi, so last night i was sitting on the ledge...      1
3  ['I tried to kill my self once and failed badl...      1
4  ['Hi NEM3030. What sorts of things do you enjo...      1

In [ ]:
Class={"Risk":1, "No risk":0}
df=df.replace({"cls":Class})
df = df.rename(columns={"cls": "class"})
df.head(10)

text  class
0                     Insert random platitude here.       0
1  It's like this in Canada. Don't ever call a he...      0
2  It has never occured to me before now that thi...      0
3  Obese people, regardless of their gender, make...      0
4  The best way to spot a hyper-macho is knowing ...      0
5  Here, talking to insomnia and memories of you....      0
6  For number one , It doesn't matter how you kil...      1
7  How melancholy to know that some stories are f...      0
8  I feel so tired, so stressed, so empty. I don'...      1
9  Everything and nothing. I returned a few days ...      0

In [ ]:
df= df.dropna()

In [ ]:
x= df.drop('class',axis=1)

In [ ]:
y=df['class']

In [ ]:
var= x.copy()

In [ ]:
var.reset_index(inplace=True)

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# DOWNLOADING THE STOPWORDS
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

In [ ]:
# TEXT PREPROCESSING
# Lemmatizer, REMOVAL OF STOP WORDS , CONVERTING INTO LOWER CASE
lemmatizer = WordNetLemmatizer()
corpus = []
for i in range(0, len(var)):
    review = re.sub('[^a-zA-Z]', ' ', var['text'][i])
    review = review.lower()
    review = review.split()

    review =  [lemmatizer.lemmatize(word) for word in review if not word in stop_words]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus[:5]

['killing dream deeply suicidal month started killing dream actually make feel happy pray killed car accident murdered back alleyway something want die want commit suicide',
 'want die dying troublesome pretty good life one guess people would love live safe country good healthcare etc etc family bit distant everyone adult life could probably stand talk friend often often bring chat linger open chat window type retype conversation starter eventually leave want talk really think friend glad see school anymore person dread seeing every class reunion know talk anyone anymore thing absence make difference anyone life leave uni space everyone thing used well nobody miss stayed alone dorm room whole week bring get go class eat sometimes nobody noticed disappeared world would move nothing would change stupid know feel like slightest thing achievement lack thereof life define person know intellectually every time fail test get call back get brushed rejected shake feeling existence mistake corre

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
voc_size=13000
onehot_repr=[one_hot(words,voc_size)for words in corpus]

In [ ]:
encoding = [one_hot(words,vocab_size) for words in corpus]
emb_docs=pad_sequences(onehot_repr,padding='pre',maxlen=20)
print(emb_docs)

[[ 6543  9828   397 ... 11064  7086  3540]
 [ 2443  1890  8108 ...  1676  4878  4557]
 [    0     0 11646 ...  9519  6965  6811]
 ...
 [    0     0     0 ...  1591  1446  8065]
 [ 1993    88 12781 ...  7263  4505  2880]
 [    0     0     0 ...  1138 10849  2108]]


In [ ]:
X = np.array(emb_docs)
labels = np.array(y)

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
kf=KFold(n_splits=5,random_state=None)
for index_train, index_test in kf.split(df):
   modelcnn = Sequential()
   modelcnn.add(Embedding(13000, 32, input_length=20))
   modelcnn.add(Conv1D(32, 3, padding='same', activation='relu'))
   modelcnn.add(MaxPooling1D())
   modelcnn.add(Flatten())
   modelcnn.add(Dense(250, activation='relu'))
   modelcnn.add(Dense(1, activation='sigmoid'))
   modelcnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
   sequence_length=X.shape[1]

   modelcnn.fit(X[index_train],labels[index_train],validation_data=(X[index_test], labels[index_test]), epochs=2, batch_size=64)




Epoch 1/2
125/125 [==============================] - 3s 13ms/step - loss: 0.4729 - accuracy: 0.7745 - val_loss: 0.3283 - val_accuracy: 0.8680
Epoch 2/2
125/125 [==============================] - 1s 11ms/step - loss: 0.2257 - accuracy: 0.9133 - val_loss: 0.3211 - val_accuracy: 0.8680
Epoch 1/2
125/125 [==============================] - 2s 12ms/step - loss: 0.4539 - accuracy: 0.7886 - val_loss: 0.3318 - val_accuracy: 0.8585
Epoch 2/2
125/125 [==============================] - 2s 14ms/step - loss: 0.2211 - accuracy: 0.9139 - val_loss: 0.3522 - val_accuracy: 0.8580
Epoch 1/2
125/125 [==============================] - 4s 18ms/step - loss: 0.4521 - accuracy: 0.7906 - val_loss: 0.3073 - val_accuracy: 0.8740
Epoch 2/2
125/125 [==============================] - 1s 11ms/step - loss: 0.2194 - accuracy: 0.9146 - val_loss: 0.3248 - val_accuracy: 0.8770
Epoch 1/2
125/125 [==============================] - 2s 12ms/step - loss: 0.4584 - accuracy: 0.7774 - val_loss: 0.3277 - val_accuracy: 0.8625
Epoch 

In [ ]:
from tensorflow.keras.layers import Flatten

In [ ]:
kf=KFold(n_splits=5,random_state=None)
for index_train, index_test in kf.split(df):
  model = Sequential()
  model.add(Embedding(voc_size, 30, input_length=20))
  model.add(Bidirectional(LSTM(128,dropout=0.2,recurrent_dropout=0.2,return_sequences=True)))
  #model.add(Bidirectional(LSTM(100,dropout=0.2,recurrent_dropout=0.2)))
  model.add(Bidirectional(LSTM(64, dropout=0.2, recurrent_dropout=0.2)))

  model.add(Dense(1,activation='sigmoid'))
  model.add(Flatten())
  #model.add(Dense(64,activation='softmax'))
  #model.add(Dense(1,activation='softmax'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  sequence_length=X.shape[1]

  model.fit(X[index_train],labels[index_train],validation_data=(X[index_test], labels[index_test]), epochs=2, batch_size=64)

Epoch 1/2
125/125 [==============================] - 43s 278ms/step - loss: 0.4253 - accuracy: 0.8167 - val_loss: 0.3051 - val_accuracy: 0.8710
Epoch 2/2
125/125 [==============================] - 33s 260ms/step - loss: 0.2291 - accuracy: 0.9137 - val_loss: 0.3174 - val_accuracy: 0.8690
Epoch 1/2
125/125 [==============================] - 43s 267ms/step - loss: 0.4232 - accuracy: 0.8059 - val_loss: 0.3629 - val_accuracy: 0.8460
Epoch 2/2
125/125 [==============================] - 32s 256ms/step - loss: 0.2241 - accuracy: 0.9115 - val_loss: 0.3349 - val_accuracy: 0.8620
Epoch 1/2
125/125 [==============================] - 44s 283ms/step - loss: 0.4197 - accuracy: 0.8010 - val_loss: 0.3114 - val_accuracy: 0.8745
Epoch 2/2
125/125 [==============================] - 35s 276ms/step - loss: 0.2252 - accuracy: 0.9141 - val_loss: 0.3304 - val_accuracy: 0.8710
Epoch 1/2
125/125 [==============================] - 43s 276ms/step - loss: 0.4175 - accuracy: 0.8006 - val_loss: 0.3361 - val_accuracy:

In [ ]:
max_words = 20
top_words = 13000
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from tensorflow.keras.layers import Flatten

In [ ]:
kf=KFold(n_splits=5,random_state=None)
for index_train, index_test in kf.split(df):
  modellstm = Sequential()
  modellstm.add(Embedding(voc_size, 30, input_length=20))
  modellstm.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2,return_sequences=True))
  #model.add(Bidirectional(LSTM(100,dropout=0.2,recurrent_dropout=0.2)))
  modellstm.add(LSTM(64, dropout=0.2, recurrent_dropout=0.2))

  modellstm.add(Dense(1,activation='sigmoid'))
  modellstm.add(Flatten())
  #model.add(Dense(64,activation='softmax'))
  #model.add(Dense(1,activation='softmax'))
  modellstm.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  sequence_length=X.shape[1]
  model.fit(X[index_train],labels[index_train],validation_data=(X[index_test], labels[index_test]), epochs=2, batch_size=64)


Epoch 1/2
125/125 [==============================] - 35s 283ms/step - loss: 0.2046 - accuracy: 0.9262 - val_loss: 0.1634 - val_accuracy: 0.9395
Epoch 2/2
125/125 [==============================] - 34s 276ms/step - loss: 0.1323 - accuracy: 0.9569 - val_loss: 0.2047 - val_accuracy: 0.9250
Epoch 1/2
125/125 [==============================] - 33s 265ms/step - loss: 0.1323 - accuracy: 0.9553 - val_loss: 0.1005 - val_accuracy: 0.9750
Epoch 2/2
125/125 [==============================] - 33s 262ms/step - loss: 0.0868 - accuracy: 0.9730 - val_loss: 0.1140 - val_accuracy: 0.9605
Epoch 1/2
109/125 [=========================>....] - ETA: 3s - loss: 0.0834 - accuracy: 0.9752

KeyboardInterrupt: ignored