In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
#NLP Libraries
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [ ]:
#Deep Learning Libraries
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Bidirectional

#Vocabulary Size
vocab_size=5000

In [ ]:
#Mount at drive
import sys
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


FOR SWMH DATASET

In [ ]:
dftrain= pd.read_csv('/content/drive/MyDrive/Identifying Suicidal Intent through Depression Detection from Texts using Machine Learning Techniques/Dataset/Original Dataset/swnh/train.csv')
dftrain.head(10)

text              label
0  wanting to skip or postpone my exam my exam is...       self.Anxiety
1  Do other bipolar folks have problems with subs...       self.bipolar
2  Wanted to share some revelations I just had to...    self.depression
3  I feel deader than dead. I find that I don't h...  self.SuicideWatch
4  I'm pretty sure my friends suicidal what do I ...  self.SuicideWatch
5  Self-harm urges are getting stronger Hey every...    self.depression
6  Anonymous Entry: plz be nice My brain boils no...    self.depression
7  I'm drowning. I don't remember ever really bei...    self.depression
8  ANYONE here ever tried r-TMS (repeated Transcr...       self.bipolar
9  Anyone else just afraid of life? First off, if...    self.depression

In [ ]:

Class={'self.Anxiety':0, 'self.bipolar':0, 'self.depression':1,'self.SuicideWatch':1, 'self.offmychest':0}
dftrain=dftrain.replace({"label":Class})
dftrain = dftrain.rename(columns={"label": "class"})
dftrain.head(10)

text  class
0  wanting to skip or postpone my exam my exam is...      0
1  Do other bipolar folks have problems with subs...      0
2  Wanted to share some revelations I just had to...      1
3  I feel deader than dead. I find that I don't h...      1
4  I'm pretty sure my friends suicidal what do I ...      1
5  Self-harm urges are getting stronger Hey every...      1
6  Anonymous Entry: plz be nice My brain boils no...      1
7  I'm drowning. I don't remember ever really bei...      1
8  ANYONE here ever tried r-TMS (repeated Transcr...      0
9  Anyone else just afraid of life? First off, if...      1

In [ ]:
df=dftrain.dropna()

In [ ]:
x= df.drop('class',axis=1)

In [ ]:
ytrain=df['class']

In [ ]:
var= x.copy()

In [ ]:
var.reset_index(inplace=True)

In [ ]:
# DOWNLOADING THE STOPWORDS
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
# TEXT PREPROCESSING
# Lemmatizer, REMOVAL OF STOP WORDS , CONVERTING INTO LOWER CASE
lemmatizer = WordNetLemmatizer()
corpus = []
for i in range(0, len(var)):
    review = re.sub('[^a-zA-Z]', ' ', var['text'][i])
    review = review.lower()
    review = review.split()

    review =  [lemmatizer.lemmatize(word) for word in review if not word in stop_words]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus[:5]

['want skip postpon exam exam saturday feel massiv urg reschedul experi often major exam flashback sever year prior skip final exam fail dont feel readi dont know im tire mentallli fri feel day might help part think fight urg tank',
 'bipolar folk problem substanc abus first want say great abl talk thing open way never good point term drug alcohol right big problem past od mani time time intent suicid attempt total care happen extrem distress usual abus mother occur space decad fuck bad alcohol methadon end icu doctor told larg number bipolar peopl addict problem take med exactli prescrib drug use marijuana problem other similar problem',
 'want share revel tonight depress first time year hope thing get better hi depress year still depress first time throughout hell actual gain insight hope thing get better realli breath fresh air depress liter suffoc long know necessarili appli everyon realli hope share mayb give peopl insight hope well first thought depress result loneli abl function

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
voc_size=13000
onehot_repr=[one_hot(words,voc_size)for words in corpus]

In [ ]:
encoding = [one_hot(words,vocab_size) for words in corpus]
emb_docs=pad_sequences(onehot_repr,padding='pre',maxlen=20)
print(emb_docs)

[[11617  9333  7289 ...  7645 12586  5430]
 [ 6846  8261  9097 ...  6148    96  8850]
 [11824  3516  3406 ...  8168  8534  6165]
 ...
 [10321  5824  5777 ...  8930  9824  6086]
 [ 6457  8205  9681 ...  8725   189  6171]
 [ 5777  8850 10827 ...  8725  4779  7069]]


In [ ]:
x_train= np.array(emb_docs)
y_train = np.array(y)

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Identifying Suicidal Intent through Depression Detection from Texts using Machine Learning Techniques/Dataset/Original Dataset/Suicide and Depression Detection.csv')
df.head(10)

Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1           3  Am I weird I don't get affected by compliments...  non-suicide
2           4  Finally 2020 is almost over... So I can never ...  non-suicide
3           8          i need helpjust help me im crying so hard      suicide
4           9  I’m so lostHello, my name is Adam (16) and I’v...      suicide
5          11  Honetly idkI dont know what im even doing here...      suicide
6          12  [Trigger warning] Excuse for self inflicted bu...      suicide
7          13   It ends tonight.I can’t do it anymore. \nI quit.      suicide
8          16  Everyone wants to be "edgy" and it's making me...  non-suicide
9          18  My life is over at 20 years oldHello all. I am...      suicide

In [ ]:
df.shape

(1895, 14)

SWMH DATASET TEST



In [ ]:
Class={'self.Anxiety':0, 'self.bipolar':0, 'self.depression':1,'self.SuicideWatch':1, 'self.offmychest':0}
df=df.replace({"label":Class})
df = df.rename(columns={"label": "class"})
df.head(10)

text  class
0  wanting to skip or postpone my exam my exam is...      0
1  Do other bipolar folks have problems with subs...      0
2  Wanted to share some revelations I just had to...      1
3  I feel deader than dead. I find that I don't h...      1
4  I'm pretty sure my friends suicidal what do I ...      1
5  Self-harm urges are getting stronger Hey every...      1
6  Anonymous Entry: plz be nice My brain boils no...      1
7  I'm drowning. I don't remember ever really bei...      1
8  ANYONE here ever tried r-TMS (repeated Transcr...      0
9  Anyone else just afraid of life? First off, if...      1

CEASE DATASET


In [ ]:
df.drop(["Unnamed: 0", "Positive", "Negative", "Neutral", "Compound"],axis=1, inplace=True)
df = df.rename(columns={"Sentiment": "class"})
df.head(10)

text  class
0  after all i was stupid to be used because i wo...      0
1  of course ido not want to die but it is suffer...      0
2  whatever this new accusation is it has beaten ...      0
3  passed in great anxiety finally painted the ba...      0
4  the most charming intelligent and important pe...      1
5  it has prevented my getting anything like the ...      1
6  i hve receved hate letters telling me to leave...      0
7                  i was burning in hell every day .      0
8  or write faggot on my locker or send me letter...      0
9  it is like they beat the hellout of me with th...      0

Life Corpus

In [ ]:
Class={"Risk":1, "No risk":0}
df=df.replace({"cls":Class})
df = df.rename(columns={"cls": "class"})
df.head(10)

text  class
0                     Insert random platitude here.       0
1  It's like this in Canada. Don't ever call a he...      0
2  It has never occured to me before now that thi...      0
3  Obese people, regardless of their gender, make...      0
4  The best way to spot a hyper-macho is knowing ...      0
5  Here, talking to insomnia and memories of you....      0
6  For number one , It doesn't matter how you kil...      1
7  How melancholy to know that some stories are f...      0
8  I feel so tired, so stressed, so empty. I don'...      1
9  Everything and nothing. I returned a few days ...      0

500 Reddit post

In [ ]:
df.drop(["User"],axis=1, inplace=True)
Class= {"Ideation": 1, "Supportive": 0,"Attempt":1,"Behavior":1,"Indicator":1}
df = df.rename(columns={"Post": "text"})
df=df.replace({"Label":Class})
df = df.rename(columns={"Label": "class"})
df.head()


text  class
0  ['Its not a viable option, and youll be leavin...      0
1  ['It can be hard to appreciate the notion that...      1
2  ['Hi, so last night i was sitting on the ledge...      1
3  ['I tried to kill my self once and failed badl...      1
4  ['Hi NEM3030. What sorts of things do you enjo...      1

Suicide and Depression Detection

In [ ]:
df.drop(["Unnamed: 0"],axis=1, inplace=True)
Class={"non-suicide":0,"suicide":1}
df=df.replace({"class":Class})
df.head(10)

text  class
0  Ex Wife Threatening SuicideRecently I left my ...      1
1  Am I weird I don't get affected by compliments...      0
2  Finally 2020 is almost over... So I can never ...      0
3          i need helpjust help me im crying so hard      1
4  I’m so lostHello, my name is Adam (16) and I’v...      1
5  Honetly idkI dont know what im even doing here...      1
6  [Trigger warning] Excuse for self inflicted bu...      1
7   It ends tonight.I can’t do it anymore. \nI quit.      1
8  Everyone wants to be "edgy" and it's making me...      0
9  My life is over at 20 years oldHello all. I am...      1

In [ ]:
df_manual_testing = df.tail(30000)
for i in range(1,30001,-1):
    df.drop([i], axis = 0, inplace = True)

In [ ]:
df_manual_testing.shape

(30000, 2)

In [ ]:
df=df_manual_testing

SDCNL

In [ ]:
df.drop(["Unnamed: 0","Unnamed: 0.1","title","selftext","author","num_comments","url","title_clean","author_clean","selftext_length","title_length","megatext_clean"], axis=1, inplace=True)
df = df.rename(columns={"selftext_clean": "text"})
df = df.rename(columns={"is_suicide": "class"})
df.head(10)

class                                               text
0      0  hi really know phrase situation try life reall...
1      1  depressed past couple week ever since got back...
2      0  hi know else go devastated right feeling like ...
3      1  shit like get better everyone purpose need fin...
4      0  wish wa prettier wish feel like burden wish br...
5      1  weird question someplace call talk someone go ...
6      0  venting void feel bad constantly annoying frie...
7      0  hey guy last week went roughest day ocd ha eve...
8      1  know pas know many people know care want say p...
9      0  fighting depression couple year ha uphill batt...

RUN FOR ALL

In [ ]:
df= df.dropna()

In [ ]:
x= df.drop('class',axis=1)

In [ ]:
y=df['class']

In [ ]:
var= x.copy()

In [ ]:
var.reset_index(inplace=True)

In [ ]:
# DOWNLOADING THE STOPWORDS
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
# TEXT PREPROCESSING
# STEMMING, REMOVAL OF STOP WORDS , CONVERTING INTO LOWER CASE
stemmer = PorterStemmer()
corpus1 = []
for i in range(0, len(var)):
    review = re.sub('[^a-zA-Z]', ' ', var['text'][i])
    review = review.lower()
    review = review.split()

    review = [stemmer.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus1.append(review)

In [ ]:
corpus1[:5]

['hi realli know phrase situat tri life realli good point right never realli depress stuff percent time mind clear graduat high school realli excit howev peopl famili friend group ton issu wether sleep day hate ambit keep live world got problem wanna sound like gloat usual person lot peopl end go usual abl talk peopl issu help long run yeah sometim issu make realli sad stuff feel sad peopl tell feel worthless today one best friend show wa cut realli effect talk mostli pain bore even know pretti logic guy go class sit hour time noth challeng way school work ha clinic diagnos depress ha psychiatr ward see therapist regularli coupl hour sinc show arm even see got two main problem right first realli know help said liter thing realli hang school weekend sit bed day tri make effort much need said long go highschool consid law go feel way graduat need know someth help tell parent therapist help alreadi go one talk tomorrow know second stuff like realli effect feel world unfair everyon care wa

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
voc_size=13000
onehot_repr=[one_hot(words,voc_size)for words in corpus]

In [ ]:
encoding = [one_hot(words,vocab_size) for words in corpus1]
emb_docs=pad_sequences(onehot_repr,padding='pre',maxlen=20)
print(emb_docs)

[[    0     0     0 ...  2493  5881  7961]
 [ 3004  5252  5437 ...  5732  4700  7346]
 [ 4503 10661  3406 ...  2249  1046   601]
 ...
 [10440 12786  4879 ...  2493 12494  1011]
 [ 2241  6076  1557 ... 10136  8665  4332]
 [10073  2077  7522 ...  5094   906  5824]]


swmh test data


In [ ]:
x_test = np.array(emb_docs)
y_test = np.array(y)

In [ ]:
final_x = np.array(emb_docs)
final_y = np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(final_x, final_y, test_size=0.2, random_state=0)

In [ ]:
from tensorflow.keras.layers import Flatten

Bidirectional LSTM


In [ ]:
model = Sequential()
model.add(Embedding(voc_size, 30, input_length=20))
model.add(Bidirectional(LSTM(128,dropout=0.2,recurrent_dropout=0.2,return_sequences=True)))
#model.add(Bidirectional(LSTM(100,dropout=0.2,recurrent_dropout=0.2)))
model.add(Bidirectional(LSTM(64, dropout=0.2, recurrent_dropout=0.2)))

model.add(Dense(1,activation='sigmoid'))
model.add(Flatten())
#model.add(Dense(64,activation='softmax'))
#model.add(Dense(1,activation='softmax'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 30)            390000    
                                                                 
 bidirectional_2 (Bidirectio  (None, 20, 256)          162816    
 nal)                                                            
                                                                 
 bidirectional_3 (Bidirectio  (None, 128)              164352    
 nal)                                                            
                                                                 
 dense_1 (Dense)             (None, 1)                 129       
                                                                 
 flatten (Flatten)           (None, 1)                 0         
                                                                 
Total params: 717,297
Trainable params: 717,297
Non-tr

In [ ]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=4, batch_size=64)

Epoch 1/4
545/545 [==============================] - 200s 336ms/step - loss: 0.5456 - accuracy: 0.7141 - val_loss: 0.5256 - val_accuracy: 0.7333
Epoch 2/4
545/545 [==============================] - 175s 322ms/step - loss: 0.4839 - accuracy: 0.7669 - val_loss: 0.5256 - val_accuracy: 0.7356
Epoch 3/4
545/545 [==============================] - 179s 328ms/step - loss: 0.4537 - accuracy: 0.7870 - val_loss: 0.5331 - val_accuracy: 0.7285
Epoch 4/4
545/545 [==============================] - 180s 331ms/step - loss: 0.4285 - accuracy: 0.8030 - val_loss: 0.5451 - val_accuracy: 0.7311


In [ ]:
y_pred= (model.predict(x_test)>0.5).astype("int32")


341/341 [==============================] - 12s 31ms/step


In [ ]:
print(confusion_matrix(y_test, y_pred))

[[3379 1712]
 [1214 4578]]


In [ ]:
print(accuracy_score(y_test, y_pred))

0.7311403105761279


CNN model

In [ ]:
max_words = 20
top_words = 13000
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [ ]:
modelcnn = Sequential()
modelcnn.add(Embedding(top_words, 32, input_length=max_words))
modelcnn.add(Conv1D(32, 3, padding='same', activation='relu'))
modelcnn.add(MaxPooling1D())
modelcnn.add(Flatten())
modelcnn.add(Dense(250, activation='relu'))
modelcnn.add(Dense(1, activation='sigmoid'))
modelcnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
modelcnn.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 32)            416000    
                                                                 
 conv1d (Conv1D)             (None, 20, 32)            3104      
                                                                 
 max_pooling1d (MaxPooling1D  (None, 10, 32)           0         
 )                                                               
                                                                 
 flatten_1 (Flatten)         (None, 320)               0         
                                                                 
 dense_2 (Dense)             (None, 250)               80250     
                                                                 
 dense_3 (Dense)             (None, 1)                 251       
                                                      

In [ ]:
modelcnn.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size=64,verbose=2)

Epoch 1/5
545/545 - 8s - loss: 0.5520 - accuracy: 0.7044 - val_loss: 0.5208 - val_accuracy: 0.7385 - 8s/epoch - 14ms/step
Epoch 2/5
545/545 - 8s - loss: 0.4555 - accuracy: 0.7874 - val_loss: 0.5499 - val_accuracy: 0.7262 - 8s/epoch - 14ms/step
Epoch 3/5
545/545 - 6s - loss: 0.3511 - accuracy: 0.8506 - val_loss: 0.6186 - val_accuracy: 0.7083 - 6s/epoch - 12ms/step
Epoch 4/5
545/545 - 8s - loss: 0.2210 - accuracy: 0.9136 - val_loss: 0.7986 - val_accuracy: 0.6910 - 8s/epoch - 14ms/step
Epoch 5/5
545/545 - 6s - loss: 0.1308 - accuracy: 0.9536 - val_loss: 1.0636 - val_accuracy: 0.6876 - 6s/epoch - 11ms/step


In [ ]:
y_predcnn= (modelcnn.predict(x_test)>0.5).astype("int32")
print(confusion_matrix(y_test, y_predcnn))

341/341 [==============================] - 1s 2ms/step
[[3316 1775]
 [1625 4167]]


In [ ]:
print(accuracy_score(y_test, y_predcnn))

0.6875861435266011


LSTM


In [ ]:
modellstm = Sequential()
modellstm.add(Embedding(voc_size, 30, input_length=20))
modellstm.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2,return_sequences=True))
#model.add(Bidirectional(LSTM(100,dropout=0.2,recurrent_dropout=0.2)))
modellstm.add(LSTM(64, dropout=0.2, recurrent_dropout=0.2))

modellstm.add(Dense(1,activation='sigmoid'))
modellstm.add(Flatten())
#model.add(Dense(64,activation='softmax'))
#model.add(Dense(1,activation='softmax'))
modellstm.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(modellstm.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 30)            390000    
                                                                 
 lstm_4 (LSTM)               (None, 20, 128)           81408     
                                                                 
 lstm_5 (LSTM)               (None, 64)                49408     
                                                                 
 dense_4 (Dense)             (None, 1)                 65        
                                                                 
 flatten_2 (Flatten)         (None, 1)                 0         
                                                                 
Total params: 520,881
Trainable params: 520,881
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
modellstm.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
545/545 [==============================] - 86s 143ms/step - loss: 0.5524 - accuracy: 0.7125 - val_loss: 0.5288 - val_accuracy: 0.7345
Epoch 2/10
545/545 [==============================] - 88s 161ms/step - loss: 0.4875 - accuracy: 0.7636 - val_loss: 0.5236 - val_accuracy: 0.7370
Epoch 3/10
545/545 [==============================] - 80s 147ms/step - loss: 0.4585 - accuracy: 0.7857 - val_loss: 0.5345 - val_accuracy: 0.7375
Epoch 4/10
545/545 [==============================] - 79s 145ms/step - loss: 0.4313 - accuracy: 0.8032 - val_loss: 0.5498 - val_accuracy: 0.7329
Epoch 5/10
545/545 [==============================] - 76s 140ms/step - loss: 0.4082 - accuracy: 0.8159 - val_loss: 0.5587 - val_accuracy: 0.7256
Epoch 6/10
545/545 [==============================] - 79s 145ms/step - loss: 0.3878 - accuracy: 0.8285 - val_loss: 0.5845 - val_accuracy: 0.7248
Epoch 7/10
545/545 [==============================] - 79s 144ms/step - loss: 0.3659 - accuracy: 0.8408 - val_loss: 0.6213 - val_ac

In [ ]:
y_predlstm= (modellstm.predict(x_test)>0.5).astype("int32")
print(confusion_matrix(y_test, y_predlstm))

341/341 [==============================] - 7s 19ms/step
[[3361 1730]
 [1401 4391]]


In [ ]:
print(accuracy_score(y_test, y_predlstm))

0.7123035927593494


Model BERT


In [ ]:
import tensorflow_hub as hub
import tensorflow as tf
!pip install -q -U "tensorflow-text==2.11.0"
import tensorflow_text as text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 60.9 MB/s eta 0:00:00


In [ ]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [ ]:
# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)
# Neural network layers
l = tf.keras.layers.Dropout(0.2, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(256, activation='relu', name="dense_1")(l)

l = tf.keras.layers.Dense(128, activation='relu', name="dense_2")(l)
l = tf.keras.layers.Dense(64, activation='relu', name="dense_3")(l)
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


In [ ]:
final_x = np.array(corpus1)
final_y = np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(final_x, final_y, test_size=0.2, random_state=0)

In [ ]:
x_train=np.array(corpus)
x_test=np.array(corpus1)
y_train=np.array(ytrain)
y_test=np.array(y)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size = 32)

Epoch 1/5
750/750 [==============================] - 7812s 10s/step - loss: 0.4464 - accuracy: 0.7975
Epoch 2/5
 10/750 [..............................] - ETA: 2:06:13 - loss: 0.4756 - accuracy: 0.7625

KeyboardInterrupt: ignored

In [ ]:
y_predbert= (model.predict(x_test)>0.5).astype("int32")
print(confusion_matrix(y_test, y_predbert))

12/12 [==============================] - 124s 10s/step
[[170  13]
 [157  39]]


In [ ]:
print(accuracy_score(y_test, y_predbert))

0.5514511873350924
