In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
#NLP Libraries
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [ ]:
#Deep Learning Libraries
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Bidirectional

#Vocabulary Size
vocab_size=10000

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

In [ ]:
#Mount at drive
import sys
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Identifying Suicidal Intent through Depression Detection from Texts using Machine Learning Techniques/Dataset/Original Dataset/Suicide and Depression Detection.csv')

df.shape

(232074, 3)

In [ ]:
df.head(10)

Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1           3  Am I weird I don't get affected by compliments...  non-suicide
2           4  Finally 2020 is almost over... So I can never ...  non-suicide
3           8          i need helpjust help me im crying so hard      suicide
4           9  I’m so lostHello, my name is Adam (16) and I’v...      suicide
5          11  Honetly idkI dont know what im even doing here...      suicide
6          12  [Trigger warning] Excuse for self inflicted bu...      suicide
7          13   It ends tonight.I can’t do it anymore. \nI quit.      suicide
8          16  Everyone wants to be "edgy" and it's making me...  non-suicide
9          18  My life is over at 20 years oldHello all. I am...      suicide

In [ ]:
#df=dff
#df=df_manual_testing
#df =  shuffle(df).reset_index(drop=True)
#df.drop(["Unnamed: 2", "Unnamed: 3",	"Unnamed: 4",	"Unnamed: 5",	"Unnamed: 6",	"Unnamed: 7",	"Unnamed: 8",	"Unnamed: 9"],axis=1, inplace=True)
#df.drop(["Unnamed: 0", "Positive", "Negative", "Neutral", "Compound"],axis=1, inplace=True)
#df.drop(["Unnamed: 0","Unnamed: 0.1","title","selftext","author","num_comments","url","title_clean","author_clean","selftext_length","title_length","megatext_clean"], axis=1, inplace=True)
#Class= {"Ideation": 1, "Supportive": 0,"Attempt":1,"Behavior":1,"Indicator":1}
#Class={'self.Anxiety':0, 'self.bipolar':0, 'self.depression':1,'self.SuicideWatch':1, 'self.offmychest':0}
#Class={"No risk":0,"Risk":1}
Class={"non-suicide":0,"suicide":1}
df=df.replace({"class":Class})
#df = df.rename(columns={"label": "class"})
#df = df.rename(columns={"Post": "text"})
df.head(10)

Unnamed: 0                                               text  class
0           2  Ex Wife Threatening SuicideRecently I left my ...      1
1           3  Am I weird I don't get affected by compliments...      0
2           4  Finally 2020 is almost over... So I can never ...      0
3           8          i need helpjust help me im crying so hard      1
4           9  I’m so lostHello, my name is Adam (16) and I’v...      1
5          11  Honetly idkI dont know what im even doing here...      1
6          12  [Trigger warning] Excuse for self inflicted bu...      1
7          13   It ends tonight.I can’t do it anymore. \nI quit.      1
8          16  Everyone wants to be "edgy" and it's making me...      0
9          18  My life is over at 20 years oldHello all. I am...      1

In [ ]:
df_manual_testing = df.tail(30000)
for i in range(1,30001,-1):
    df.drop([i], axis = 0, inplace = True)
df=df_manual_testing

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
# TEXT PREPROCESSING
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))
# Lemmatizer, REMOVAL OF STOP WORDS , CONVERTING INTO LOWER CASE
lemmatizer = WordNetLemmatizer()
corpus1 = []
for i in range(len(df)):
    review = re.sub('[^a-zA-Z]', ' ', str(df['text'].iloc[i]))
    review = review.lower()
    review = review.split()

    review =  [lemmatizer.lemmatize(word) for word in review if not word in stop_words]
    review = ' '.join(review)
    corpus1.append(review)

In [ ]:
corpus1[:5]

['trying happy knowing dead soonit worth trying get help anymore man rushing suicide eventually run grew kinda normally mom dad divorced like became asshole hurt people broke thing hated everything lived mental hospital year basically till around time learned family secret dad biological father mom rightfully hate got sent boot camp basically lived like fucking animal zoo fat nerdy ginger kid always fucking got started violent outburst happen since got rejected friend guy girl knew bi turned open family belief also tried kill real always made weak attempt attention one actually take life also never stayed school bullied lot used failed attempt try get help nobody cared everything hurt tried warn everyone killing guess boy cried wolf long lost effect gonna worry wrinkle brow cuz nothing ever gonna alright matter struggle strive never get world alive',
 'stop mind jumping suicide time like devil shoulder whispering time something go wrong growing life seemed hopeless parent abuse away wi

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
voc_size=10000
onehot_repr=[one_hot(words,voc_size)for words in corpus1]

encoding = [one_hot(words,vocab_size) for words in corpus1]
emb_docs=pad_sequences(onehot_repr,padding='pre',maxlen=20)
print(emb_docs)

[[6344 2795 7325 ... 5299 4367  963]
 [1210 7239 8320 ... 2199 1210  580]
 [   0    0    0 ... 7755 5470 6469]
 ...
 [   0    0    0 ... 9801  800 2526]
 [9438 8950 5280 ... 8012  803 6748]
 [   0    0    0 ... 1665 6353 8117]]


In [ ]:
nltk.download('vader_lexicon')
sid = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


In [ ]:
from tensorflow.keras.layers import Flatten
import keras

LSTM

In [ ]:
def create_model():
    modellstm = Sequential()
    modellstm.add(Embedding(voc_size, 30, input_length=20))
    modellstm.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2, return_sequences=True))
    modellstm.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
    #modellstm.add(LSTM(64, dropout=0.1, recurrent_dropout=0.1))
    modellstm.add(Dense(64, activation='relu'))
    modellstm.add(Dense(1, activation='sigmoid'))
    modellstm.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


  #modellstm.compile(loss='binary_crossentropy',optimizer=keras.optimizers.RMSprop(learning_rate=1e-4),metrics=[tf.keras.metrics.BinaryAccuracy()])
    print(modellstm.summary())
    return modellstm



In [ ]:
lstm=create_model()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 30)            300000    
                                                                 
 lstm_2 (LSTM)               (None, 20, 128)           81408     
                                                                 
 lstm_3 (LSTM)               (None, 128)               131584    
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 521,313
Trainable params: 521,313
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
y=df['class']

10 fold

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score, KFold


In [ ]:
num_folds = 5
kfold = KFold(n_splits=num_folds)
accuracy_scores = []
emb_docs=np.array(emb_docs)
y=np.array(y)


for train_indices, test_indices in kfold.split(emb_docs,y):
    train_data = df.iloc[train_indices]
    test_data = df.iloc[test_indices]
    X_train, X_test = emb_docs[train_indices], emb_docs[test_indices]
    Y_train, Y_test = y[train_indices], y[test_indices]

    lstm.fit(X_train, Y_train, epochs=10, batch_size=64)

    lstm_predictions = lstm.predict(X_test)
    #print(lstm_predictions)
    # Calculate sentiment scores for the current fold's test set
    test_sentiment_scores = [sid.polarity_scores(str(text))["compound"] for text in test_data["text"]]

    combined_features = np.column_stack((lstm_predictions[:len(test_sentiment_scores)], test_sentiment_scores))
    #print(combined_features)

    svm = LinearSVC()
    svm.fit(combined_features, Y_test[:len(combined_features)])

    svm_predictions = svm.predict(combined_features)
    print(svm_predictions)
    accuracy = accuracy_score(Y_test[:len(combined_features)], svm_predictions)
    accuracy_scores.append(accuracy)


Epoch 1/10
375/375 [==============================] - 80s 188ms/step - loss: 0.3685 - accuracy: 0.8459
Epoch 2/10
375/375 [==============================] - 64s 170ms/step - loss: 0.2502 - accuracy: 0.9011
Epoch 3/10
375/375 [==============================] - 59s 158ms/step - loss: 0.2127 - accuracy: 0.9193
Epoch 4/10
375/375 [==============================] - 59s 159ms/step - loss: 0.1823 - accuracy: 0.9330
Epoch 5/10
375/375 [==============================] - 59s 156ms/step - loss: 0.1570 - accuracy: 0.9440
Epoch 6/10
375/375 [==============================] - 58s 156ms/step - loss: 0.1361 - accuracy: 0.9507
Epoch 7/10
375/375 [==============================] - 58s 156ms/step - loss: 0.1159 - accuracy: 0.9601
Epoch 8/10
375/375 [==============================] - 58s 156ms/step - loss: 0.0976 - accuracy: 0.9665
Epoch 9/10
375/375 [==============================] - 58s 155ms/step - loss: 0.0864 - accuracy: 0.9700
Epoch 10/10
188/188 [==============================] - 5s 21ms/step
[1 1 

In [ ]:
print(np.mean(accuracy_scores))

0.9372333333333334


In [ ]:
import joblib

joblib.dump(svm, '/content/drive/MyDrive/Identifying Suicidal Intent through Depression Detection from Texts using Machine Learning Techniques/model/SVM_MODEL.pkl')

['/content/drive/MyDrive/Identifying Suicidal Intent through Depression Detection from Texts using Machine Learning Techniques/model/SVM_MODEL.pkl']

In [ ]:
lstm.save('/content/drive/MyDrive/Identifying Suicidal Intent through Depression Detection from Texts using Machine Learning Techniques/model/LSTM_model.h5')